---
# file: cookie.yml
# Playbook for installing igsp_web_cookie (cookieDaemon, verifyCookie, and signCookie)
# group_vars for cookiedev hosts are encrypted - include database connection and cert/key
- hosts: cookiedev
  roles:
    - igsp_web_cookie
