# This playbook requires the angstwad.docker_ubuntu role
# Install it with `ansible-galaxy install angstwad.docker_ubuntu`
- name: Install Docker
  hosts: docker
  sudo: yes
  vars:
    update_docker_package: yes
  roles:
    - angstwad.docker_ubuntu
