- name: Deploy webserver for viewing predictions inside Docker
  hosts: imads
  become: yes
  roles:
    - { role: RDI2.docker, when: "ansible_os_family == 'RedHat'" }
    - { role: angstwad.docker_ubuntu, when: "ansible_os_family == 'Debian'" }
    - docker_webapp
    - imads_webapp
