- include: tasks/python_https_fixes.yml

- name: Creates predictions data directory shared by portal and worker
  file: path=/pred_data state=directory

- include: tasks/setup_postgres.yml db_state=reloaded db_config=normal

- stat: path=/pred_data/loaded.txt
  register: pred_data_loaded

- name: Setup loading postgres configuration
  when: pred_data_loaded.stat.isreg is not defined
  blockinfile:
    dest: /var/lib/postgresql/data/postgresql.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    content: |
      maintenance_work_mem = 2048MB
      fsync = off

- include: tasks/setup_postgres.yml db_state=restarted db_config=load
  when: pred_data_loaded.stat.isreg is not defined

- name: Initial download and load database with prediction data
  when: pred_data_loaded.stat.isreg is not defined
  docker:
    image: dukegcb/tf-dna-predictions
    net: "{{ tf_dna_predictions.network }}"
    env: "{{ tf_dna_predictions.env }}"
    command: python load.py all
    detach: False
    volumes:
      - /etc/external/:/etc/external/
      - /pred_data:/tmp/pred_data
    pull: always

- name: Create finished loading text file
  when: pred_data_loaded.stat.isreg is not defined
  command: touch /pred_data/loaded.txt

- name: Setup production postgres configuration (1/4 RAM shared_buffers, memory for sorting)
  blockinfile:
    dest: /var/lib/postgresql/data/postgresql.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    content: |
      shared_buffers = 4GB
      work_mem = 48MB
      logging_collector = on
      log_directory = 'pg_log'
      log_min_duration_statement = 30

- include: tasks/setup_postgres.yml db_state=restarted  db_config=production
  when: pred_data_loaded.stat.isreg is not defined

- include: tasks/setup_portal.yml

- include: tasks/setup_vacuum.yml

- include: tasks/setup_worker.yml

