# Worker process that creates predictions for jobs created by the portal.
# This requires /pred_data/models directory to already contain tracks.yaml and appropriate *.model files.
# This requires /pred_data/work directory it will use for temporary storage.

- name: Create predictions worker container
  docker:
    name: worker
    image: dukegcb/predict-tf-binding-worker
    net: "{{ tf_dna_predictions.network }}"
    env: "{{ tf_dna_predictions.env }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - /pred_data/models:/pred_data/models:ro
      - /pred_data/work:/pred_data/work:rw
    pull: always
    state: reloaded
    restart_policy: always

# Using command-line docker pull here because ansible docker_image module is unpredictable.
# Version 2.0 fails if there are any untagged docker images. 2.1 appears to fix
# but would require a force flag to fetch updates, which shouldn't be necessary
- name: Pull latest predictions docker image
  command: docker pull dukegcb/predict-tf-binding:latest
