# Worker process that creates predictions for jobs created by the portal.
# This requires /pred_data/models directory to already contain tracks.yaml and appropriate *.model files.
# This requires /pred_data/work directory it will use for temporary storage.

- name: Create predictions worker container
  docker:
    name: worker
    image: dukegcb/predict-tf-binding-worker
    net: "{{ tf_dna_predictions.network }}"
    env: "{{ tf_dna_predictions.env }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - /pred_data/models:/pred_data/models:ro
      - /pred_data/work:/pred_data/work:rw
    restart_policy: always