- name: Create Database container
  docker:
    image: postgres:9.5
    name: db
    net: "{{ handover_service.network }}"
    env: "{{ handover_service.env }}"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    pull: always
    state: reloaded
    restart_policy: always
- name: Run initial database migration
  docker:
    image: dukegcb/dukedshandoverservice-apache
    net: "{{ handover_service.network }}"
    command: python manage.py migrate
    detach: False
    env: "{{ handover_service.env }}"
    volumes:
      - /etc/external/:/etc/external/
    pull: always
- name: Create app container
  docker:
    image: dukegcb/dukedshandoverservice-apache
    name: web
    net: "{{ handover_service.network }}"
    env: "{{ handover_service.env }}"
    volumes:
      - /etc/external/:/etc/external/
    ports:
      - "80:80"
      - "443:443"
    pull: always
    state: reloaded
    restart_policy: always
