- name: Set OS-dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    - ../vars/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml
    - ../vars/{{ ansible_distribution }}.yml
    - ../vars/{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml
    - ../vars/{{ ansible_os_family }}.yml

- name: Install Duo
  include: "{{ duounix_install }}.yml"

- name: Place PAM config file
  template: >
    src=pam_duo.conf.j2
    dest={{ duounix_conf_dir }}/pam_duo.conf
  when: duounix_build_pam

- name: Place login config file
  template: >
    src=login_duo.conf.j2
    dest={{ duounix_conf_dir }}/login_duo.conf
