---
igsp_web_cookie_owner: "{{ ansible_user_id }}"
igsp_web_cookie:
  repo: https://github.com/Duke-GCB/igsp_web_cookie.git
  dest: /opt/code/
  version: master
  install_dir: /var/system/cookied
  conf_file_name: cookied.conf
  owner: "{{ igsp_web_cookie_owner }}" # for overriding without hash_merge
cookied_conf: # This must be overridden, override should be in vault!
  conf_dir: /var/system/cookied/dev-gcb
  socket_file_name: cookieDaemon.sock
  db_conn_string: //127.0.0.1:1521/SID
  db_user: user
  db_pass: pass
  private_key_file_name: key.pem
  cert_file_name: cert.pem
cookied_privatekey: |
  -----BEGIN RSA PRIVATE KEY-----
  ...
  -----END RSA PRIVATE KEY-----
cookied_cert: |
  -----BEGIN CERTIFICATE-----
  ...
  -----END CERTIFICATE-----
