---
- name: Install lmod dependencies
  yum: name={{ item }} state=present
  with_items:
    - zsh
    - lua
    - lua-filesystem
    - lua-posix
    - lua-devel

- name: Create nfs directory
  file:
    path: /nfs
    state: directory
    mode: 0755

- name: Copy bash profile
  template: src=lmod.sh.j2 dest=/etc/profile.d/lmod.sh owner=root mode=0644

- name: Copy bash and csh profiles
  template: src=lmod.csh.j2 dest=/etc/profile.d/lmod.csh owner=root mode=0644

- name: Copy zsh site-functions
  copy: src={{ item }} dest=/usr/share/zsh/site-functions/ owner=root mode=0644
  with_fileglob:
    - "_*"
