---
- name: Install packages
  when: ansible_os_family == 'RedHat'
  sudo: yes
  yum: name={{ item }}
  with_items:
    - git
    - gcc-c++
    - make
    - openssl-devel
    - openssl

- name: Make directory for code and set ownership
  file: path={{ igsp_web_cookie.dest }}
        mode=0755
        state=directory
        owner={{ ansible_user_id }}
  sudo: yes

# Clone git repo
- name: Clone igsp_web_cookie
  git: repo={{ igsp_web_cookie.repo }}
       dest={{ igsp_web_cookie.dest }}/igsp_web_cookie
       version={{ igsp_web_cookie.version }}

# Build
- name: Build igsp_web_cookie
  command: make chdir={{ igsp_web_cookie.dest }}/igsp_web_cookie
                creates={{ igsp_web_cookie.dest }}/igsp_web_cookie/bin/verifyCookie

# Create & set ownership on install dir
- name: Create install dir
  file: path={{ igsp_web_cookie.install_dir }}
        mode=0755
        state=directory
        owner={{ igsp_web_cookie.owner }}
  sudo: yes

# place binaries (sudo make install)
- name: Install binaries
  command: make install prefix={{ igsp_web_cookie.install_dir }} chdir={{ igsp_web_cookie.dest }}/igsp_web_cookie
           creates={{ igsp_web_cookie.install_dir }}/verifyCookie

# Place key and certificate
- name: Place cookied private key
  copy: content="{{ cookied_privatekey }}"
        dest="{{ cookied_conf.private_key_path }}"
        owner="{{ igsp_web_cookie.owner }}"
        mode=600

- name: Place cookied certificate
  copy: content="{{ cookied_cert }}"
        dest="{{ cookied_conf.cert_path }}"
        owner="{{ igsp_web_cookie.owner }}"
        mode=600

# make config file
- name: Generate config file
  template: src=cookied.conf.j2 dest={{ igsp_web_cookie.install_dir }}{{ igsp_web_cookie.conf_file }} owner={{ igsp_web_cookie.owner }} mode=0400

# update environment variables
# place init script
# start script
