---
- name: Copy ldap.conf
  template: src=ldap.conf.j2 dest={{ ldap_conf_dir}}/ldap.conf owner=root group=root mode=0644

- name: Create cacerts dir
  file: dest={{ ldap_conf_dir }}/cacerts state=directory owner=root group=root mode=0755

- name: Copy idms-authdir.pem
  copy: src=idms-authdir.pem dest={{ ldap_conf_dir }}/cacerts/idms-authdir.pem owner=root group=root mode=0644

- name: Install OpenLDAP utils
  yum: name=openldap-clients state=latest
  when: ansible_distribution == 'RedHat'

