---

- name: Install auth packages
  #TODO separate into yum and apt for distros
  yum: name={{ item }}
  with_items:
    - sssd
    - openldap-clients
    - nscd
    - nss-pam-ldapd
    - krb5-workstation
    - sssd-krb5
    - pam_krb5

- name: Create cacert directory
  file:
    path: /etc/openldap/cacerts
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy OpenLDAP cert
  copy:
    src: idms-authdir.pem
    dest: /etc/openldap/cacerts/idms-authdir.pem
    owner: root
    group: root
    mode: 622

- name: Rehash OpenLDAP Cacerts
  command: >
    cacertdir_rehash /etc/openldap/cacerts

- name: Setup auth
  command: >
     authconfig --enablesssd --enablesssdauth --disableldap --disableldapauth --disablekrb5 --update

- name: Copy sssd conf
  action: template src=sssd.j2 dest=/etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600

- name: Reload sssd
  service:
    name: sssd
    state: restarted
