- name: Install docker py on RedHat
  yum: name=python-docker-py
  when: ansible_os_family == "RedHat"

- name: Creates predictions data directory shared by portal and worker
  file: path=/pred_data state=directory

- name: Creates models directory
  file: path=/pred_data/models state=directory

- name: Creates models directory
  file: path=/pred_data/work state=directory

# Create database

- include: tasks/setup_postgres.yml db_state=reloaded db_config=normal

- stat: path=/pred_data/loaded.txt
  register: pred_data_loaded

# Populate database

- include: tasks/setup_postgres.yml db_state=restarted db_config=load
  when: pred_data_loaded.stat.isreg is not defined

- name: Initial download and load database with prediction data
  when: pred_data_loaded.stat.isreg is not defined
  docker:
    image: dukegcb/imads
    net: "{{ imads.network }}"
    env: "{{ imads.env }}"
    command: python load.py all
    detach: False
    volumes:
      - /etc/external/:/etc/external/
      - /pred_data:/tmp/pred_data
    pull: always

- name: Create finished loading text file
  when: pred_data_loaded.stat.isreg is not defined
  command: touch /pred_data/loaded.txt

# Setup production database settings

- include: tasks/setup_postgres.yml db_state=restarted  db_config=production
  when: pred_data_loaded.stat.isreg is not defined

# Start web portal, vacuum daemon, and worker

- include: tasks/setup_portal.yml

- include: tasks/setup_vacuum.yml

- include: tasks/setup_worker.yml
