# Daemon that purges database records after certain time periods.

- name: Create database vacuum container
  docker:
    image: dukegcb/imads
    name: vacuum
    net: "{{ imads.network }}"
    env: "{{ imads.env }}"
    command: python vacuum.py 2880
    volumes:
      - /etc/external/:/etc/external/
      - /pred_data:/tmp/pred_data
    pull: always
    state: reloaded
    restart_policy: always