---

- name: Create cacert directory
  file:
    path: /etc/openldap/cacerts
    state: directory
    owner: root
    group: root
    mode: 0755
    force: no
    notify: Rehash OpenLDAP Cacerts

- name: Copy OpenLDAP cert
  copy:
    src: idms-authdir.pem
    dest: /etc/openldap/cacerts/idms-authdir.pem
    owner: root
    group: root
    mode: 622
    force: no
    notify: Rehash OpenLDAP Cacerts

- name: Setup auth
  command: >
     authconfig --enablesssd --enablesssdauth --disableldap --disableldapauth --disablekrb5 --update

- name: Copy sssd conf
  action: template src=sssd.j2 dest=/etc/sssd/sssd.conf owner=root group=root mode=0600
  notify: Reload sssd
