---
- debug: var=hostvars[inventory_hostname]

- include_vars: rhn_credentials.yml

- include: repos.yml
  become: yes

- name: Register RHN
  when: ansible_distribution == 'Red Hat Enterprise Linux'
  become: yes
  rhn_register: state=present username={{ rhn.username }} password={{ rhn.password }}

- name: Package update
  when: ansible_os_family == 'RedHat'
  become: yes
  become_method: sudo
  yum: name=* state=latest

- name: Install base packages
  when: ansible_os_family == 'RedHat'
  become: yes
  become_method: sudo
  yum: name={{ item }} state=present
  with_items: "{{ base_packages }}"

- name: Reboot
  become: yes
  become_method: sudo
  shell: "sleep 1 && shutdown -r now 'Ansible updates triggered'"
  async: 1
  poll: 0
  ignore_errors: true

- name: Waiting for server to come back
  local_action: wait_for delay=15 host={{ inventory_hostname }}
                state=started port=22

- debug: msg="System {{ inventory_hostname }} has come back from reboot"
