---
- name: duke-centos-oit install
  copy: src=duke-centos-oit.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: duke repository enable
  ini_file: dest=/etc/yum.repos.d/duke-centos-oit.repo
            section=duke-centos-oit
            option=enabled
            value=1
